---- DROP TABLE, SEQUENCE
-- 대출
DROP TABLE BOOK_LENDING;
DROP SEQUENCE SEQ_LENDING_NO;
-- 택배
DROP TABLE PARCEL;
DROP SEQUENCE SEQ_DELIVERY_NO;
-- 관심도서
DROP TABLE INTERESTING_BOOK;
DROP SEQUENCE SEQ_INTEREST_NO;
-- 예약
DROP TABLE BOOK_RESERVATION;
DROP SEQUENCE SEQ_RSV_NO;
-- 희망도서
DROP TABLE WISH_BOOK;
DROP SEQUENCE SEQ_APPLYNUM;
-- 서평
DROP TABLE REVIEW;
DROP SEQUENCE SEQ_REVIEWNUM;
-- 취향설문
DROP TABLE TASTE_SURVEY;
-- 취향
DROP TABLE TASTE;
-- 인기키워드
DROP TABLE POPULAR_KEYWORD;
-- 공지사항
DROP TABLE NOTICE;
DROP SEQUENCE SEQ_NOTICE;
-- 문의
DROP TABLE QNA;
DROP SEQUENCE SEQ_QNA;
-- 댓글 신고
DROP TABLE REPLY_REPORT;
DROP SEQUENCE SEQ_REPLY_REPORT;
-- 게시글 신고
DROP TABLE POST_REPORT;
DROP SEQUENCE SEQ_POST_REPORT;
-- 자유게시판 댓글
DROP TABLE REPLY;
DROP SEQUENCE SEQ_REPLY;
-- 자유게시판
DROP TABLE POST;
DROP SEQUENCE SEQ_POST;
-- 열람실
DROP SEQUENCE SEQ_RNUM;
DROP TABLE READINGROOM;
-- 스터디룸
DROP SEQUENCE SEQ_SNUM;
DROP TABLE STUDYROOM;
-- 도서
DROP TABLE BOOK;
DROP SEQUENCE SEQ_BOOK_NO;
-- 회원
DROP TABLE USERS;
DROP SEQUENCE SEQ_USERNUM;

---- CREATE SEQUENCE
-- 회원
CREATE SEQUENCE SEQ_USERNUM;
-- 도서
CREATE SEQUENCE SEQ_BOOK_NO;
-- 대출
CREATE SEQUENCE SEQ_LENDING_NO;
-- 택배
CREATE SEQUENCE SEQ_DELIVERY_NO;
-- 관심도서
CREATE SEQUENCE SEQ_INTEREST_NO;
-- 예약
CREATE SEQUENCE SEQ_RSV_NO;
-- 희망도서
CREATE SEQUENCE SEQ_APPLYNUM;
-- 서평
CREATE SEQUENCE SEQ_REVIEWNUM;
-- 취향설문 시퀀스 없음
-- 취향 시퀀스 없음
-- 인기키워드
-- 공지사항
CREATE SEQUENCE SEQ_NOTICE;
-- 문의
CREATE SEQUENCE SEQ_QNA;
-- 자유게시판
CREATE SEQUENCE SEQ_POST;
-- 자유게시판 댓글
CREATE SEQUENCE SEQ_REPLY;
-- 게시글 신고
CREATE SEQUENCE SEQ_POST_REPORT;
-- 댓글 신고
CREATE SEQUENCE SEQ_REPLY_REPORT;
-- 열람실
CREATE SEQUENCE SEQ_RNUM;
-- 스터디룸
CREATE SEQUENCE SEQ_SNUM;

---- CREATE TABLE / CONSTRAINT
-- 회원
CREATE TABLE "USERS" 
(	"USER_ID" VARCHAR2(20 BYTE), 
"USER_PWD" VARCHAR2(30 BYTE), 
"USER_NO" NUMBER DEFAULT 1, 
"USER_NAME" VARCHAR2(20 BYTE), 
"USER_PHONE" VARCHAR2(11 BYTE), 
"USER_TYPE" VARCHAR2(10 BYTE), 
"USER_EMAIL" VARCHAR2(100 BYTE), 
"STUDENT_ID" NUMBER, 
"MAJOR" VARCHAR2(20 BYTE), 
"PROFILE_PIC" VARCHAR2(100 BYTE), 
"ANNUAL_FEE" VARCHAR2(100 BYTE), 
"PAY_DATE" DATE DEFAULT SYSDATE, 
"ENROLL_DATE" DATE DEFAULT SYSDATE, 
"PASS_CHECK" VARCHAR2(1 BYTE) DEFAULT 'N', 
"APPROVAL_DATE" DATE DEFAULT SYSDATE, 
"END_DATE" DATE DEFAULT SYSDATE, 
"SOCIAL_ID" VARCHAR2(100 BYTE), 
"SURVEY_CHECK" VARCHAR2(1 BYTE) DEFAULT 'N', 
"LENDING_COPY" NUMBER DEFAULT 5
) ;
ALTER TABLE "USERS" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_PHONE" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_NO" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USER_PWD" NOT NULL ENABLE);
ALTER TABLE "USERS" ADD PRIMARY KEY ("USER_ID");

-- 도서
CREATE TABLE "BOOK"(
"BOOK_NO" NUMBER PRIMARY KEY, 
"BOOK_NAME" VARCHAR2(500 BYTE), 
"BOOK_WRITER" VARCHAR2(200 BYTE), 
"BOOK_SUBJECT" VARCHAR2(20 BYTE), 
"PUBLISHER" VARCHAR2(100 BYTE), 
"BOOK_YEAR" NUMBER, 
"CALL_NO" NUMBER, 
"ISBN" VARCHAR2(40 BYTE), 
"BOOK_COVER" VARCHAR2(100 BYTE), 
"THEME" VARCHAR2(30 BYTE), 
"BOOK_STATE" VARCHAR2(20 BYTE) DEFAULT '대출가능', 
"UPDATE_DATE" DATE DEFAULT SYSDATE, 
"LENDING_COUNT" NUMBER DEFAULT 0
);
ALTER TABLE "BOOK" MODIFY ("ISBN" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("CALL_NO" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("BOOK_YEAR" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("PUBLISHER" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("BOOK_SUBJECT" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("BOOK_WRITER" NOT NULL ENABLE);
ALTER TABLE "BOOK" MODIFY ("BOOK_NAME" NOT NULL ENABLE);

-- 대출
CREATE TABLE "BOOK_LENDING"(
"LENDING_NO" NUMBER, 
"LENDING_DATE" DATE DEFAULT SYSDATE, 
"RETURN_DATE" DATE, 
"EXTEND_COUNT" NUMBER DEFAULT 0, 
"RECEIVE" VARCHAR2(10 BYTE), 
"USER_ID" VARCHAR2(20 BYTE), 
"BOOK_NO" NUMBER REFERENCES BOOK(BOOK_NO) ON DELETE CASCADE,
"RETURN_STATE" VARCHAR2(1 BYTE) DEFAULT 'N'
);
ALTER TABLE "BOOK_LENDING" MODIFY ("RETURN_STATE" NOT NULL ENABLE);
ALTER TABLE "BOOK_LENDING" ADD PRIMARY KEY ("LENDING_NO");
ALTER TABLE "BOOK_LENDING" MODIFY ("RECEIVE" NOT NULL ENABLE);
ALTER TABLE "BOOK_LENDING" MODIFY ("RETURN_DATE" NOT NULL ENABLE);

-- 택배
CREATE TABLE PARCEL (
DELIVERY_NO NUMBER PRIMARY KEY,
LENDING_NO NUMBER NOT NULL,
ADDR VARCHAR2(200),
D_STATUS VARCHAR2(20) DEFAULT '대기'
);

-- 관심도서
CREATE TABLE "INTERESTING_BOOK"(
"INTEREST_NO" NUMBER, 
"BOOK_NO" NUMBER, 
"USER_ID" VARCHAR2(20) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
ALTER TABLE "INTERESTING_BOOK" ADD PRIMARY KEY ("INTEREST_NO");

-- 예약
CREATE TABLE "BOOK_RESERVATION"(
"RSV_NO" NUMBER, 
"BOOK_NO" NUMBER, 
"USER_ID" VARCHAR2(20) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
"RSV_DATE" DATE DEFAULT SYSDATE, 
"RSV_STATE" VARCHAR2(10 BYTE) DEFAULT '대기'
);
ALTER TABLE "BOOK_RESERVATION" MODIFY ("RSV_DATE" NOT NULL ENABLE);
ALTER TABLE "BOOK_RESERVATION" MODIFY ("USER_ID" NOT NULL ENABLE);
ALTER TABLE "BOOK_RESERVATION" MODIFY ("BOOK_NO" NOT NULL ENABLE);
ALTER TABLE "BOOK_RESERVATION" MODIFY ("RSV_STATE" NOT NULL ENABLE);
ALTER TABLE "BOOK_RESERVATION" ADD PRIMARY KEY ("RSV_NO");

-- 희망도서
CREATE TABLE "WISH_BOOK" 
(	"APPLY_NO" NUMBER, 
"USER_ID" VARCHAR2(20 BYTE), 
"BOOK_NAME" VARCHAR2(200 BYTE), 
"BOOK_WRITER" VARCHAR2(200 BYTE), 
"PUBLISHER" VARCHAR2(100 BYTE), 
"APPLY_STATUS" VARCHAR2(12 BYTE) DEFAULT '처리중', 
"APPLY_DATE" DATE DEFAULT SYSDATE
);
ALTER TABLE "WISH_BOOK" ADD PRIMARY KEY ("APPLY_NO");
ALTER TABLE "WISH_BOOK" MODIFY ("PUBLISHER" NOT NULL ENABLE);
ALTER TABLE "WISH_BOOK" MODIFY ("BOOK_WRITER" NOT NULL ENABLE);
ALTER TABLE "WISH_BOOK" MODIFY ("BOOK_NAME" NOT NULL ENABLE);
ALTER TABLE WISH_BOOK ADD CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;

-- 서평
CREATE TABLE "REVIEW" 
(	"REVIEW_NO" NUMBER, 
"BOOK_NO" NUMBER, 
"REVIEW_STAR" NUMBER, 
"REVIEW_CONTENTS" VARCHAR2(500 BYTE), 
"REVIEW_DATE" DATE DEFAULT SYSDATE, 
"REVIEW_STATUS" VARCHAR2(2 BYTE) DEFAULT 'N', 
"USER_ID" VARCHAR2(20 BYTE)
);
ALTER TABLE "REVIEW" ADD PRIMARY KEY ("REVIEW_NO");
ALTER TABLE "REVIEW" MODIFY ("REVIEW_CONTENTS" NOT NULL ENABLE);
ALTER TABLE "REVIEW" MODIFY ("REVIEW_STAR" NOT NULL ENABLE);
ALTER TABLE REVIEW ADD CONSTRAINT FK_BOOKNO FOREIGN KEY(BOOK_NO)   REFERENCES BOOK(BOOK_NO) ON DELETE CASCADE;
ALTER TABLE REVIEW ADD CONSTRAINT FK_WRITER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;

-- 취향설문
CREATE TABLE "TASTE_SURVEY" 
(	"USER_ID" VARCHAR2(20 BYTE), 
"BOOK_NO" NUMBER, 
"BOOK_NAME" VARCHAR2(500 BYTE), 
"BOOK_RATING" NUMBER, 
"BOOK_SUBJECT" VARCHAR2(20 BYTE), 
"THEME" VARCHAR2(50 BYTE), 
"SURVEY_DATE" DATE DEFAULT SYSDATE
);

-- 취향
CREATE TABLE "TASTE" 
(	"USER_ID" VARCHAR2(20 BYTE), 
"TASTE1" VARCHAR2(50 BYTE), 
"TASTE2" VARCHAR2(50 BYTE), 
"TASTE3" VARCHAR2(50 BYTE)
); 
ALTER TABLE "TASTE_SURVEY" MODIFY ("THEME" NOT NULL ENABLE);
ALTER TABLE "TASTE_SURVEY" MODIFY ("BOOK_SUBJECT" NOT NULL ENABLE);
ALTER TABLE "TASTE_SURVEY" MODIFY ("BOOK_RATING" NOT NULL ENABLE);
ALTER TABLE "TASTE_SURVEY" MODIFY ("BOOK_NAME" NOT NULL ENABLE);
ALTER TABLE "TASTE_SURVEY" MODIFY ("BOOK_NO" NOT NULL ENABLE);
ALTER TABLE TASTE ADD CONSTRAINT FK_TASTEUSER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;

-- 인기키워드
CREATE TABLE  "POPULAR_KEYWORD" 
(	"KEYWORD" VARCHAR2(500 BYTE), 
"SEARCH_DATE" DATE DEFAULT SYSDATE
);

-- 공지사항
CREATE TABLE "NOTICE" 
(	"NOTICE_NO" NUMBER, 
"NOTICE_TITLE" VARCHAR2(200 BYTE), 
"NOTICE_WRITER" VARCHAR2(20 BYTE), 
"N_CREATE_DATE" DATE DEFAULT SYSDATE, 
"NOTICE_CONTENTS" VARCHAR2(1000 BYTE), 
"VIEW_COUNT" NUMBER
) ;
ALTER TABLE "NOTICE" ADD PRIMARY KEY ("NOTICE_NO");
ALTER TABLE "NOTICE" MODIFY ("NOTICE_CONTENTS" NOT NULL ENABLE);
ALTER TABLE "NOTICE" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
ALTER TABLE "NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);

-- 문의
CREATE TABLE  "QNA" 
(	"QNA_NO" NUMBER, 
"USER_ID" VARCHAR2(20 BYTE), 
"REPLY_STATE" VARCHAR2(2 BYTE) DEFAULT 'N', 
"QNA_TITLE" VARCHAR2(200 BYTE), 
"QNA_CONTENT" VARCHAR2(1000 BYTE), 
"QNA_WRITEDATE" DATE DEFAULT SYSDATE, 
"REPLY_CONTENT" VARCHAR2(1000 BYTE), 
"REPLY_WRITEDATE" DATE DEFAULT SYSDATE, 
"REPLY_USERID" VARCHAR2(20 BYTE)
);
ALTER TABLE  "QNA" ADD PRIMARY KEY ("QNA_NO");
ALTER TABLE  "QNA" MODIFY ("QNA_CONTENT" NOT NULL ENABLE);
ALTER TABLE  "QNA" MODIFY ("QNA_TITLE" NOT NULL ENABLE);
ALTER TABLE  "QNA" MODIFY ("REPLY_STATE" NOT NULL ENABLE);
ALTER TABLE QNA ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;

-- 자유게시판
CREATE TABLE  "POST" 
(	"POST_NO" NUMBER, 
"POST_WRITER" VARCHAR2(20 BYTE), 
"POST_TITLE" VARCHAR2(200 BYTE), 
"POST_CONTENTS" VARCHAR2(1000 BYTE), 
"POST_DATE" DATE DEFAULT SYSDATE, 
"P_VIEW_COUNT" NUMBER DEFAULT 0
);
ALTER TABLE  "POST" ADD PRIMARY KEY ("POST_NO");
ALTER TABLE  "POST" MODIFY ("POST_CONTENTS" NOT NULL ENABLE);
ALTER TABLE  "POST" MODIFY ("POST_TITLE" NOT NULL ENABLE);
ALTER TABLE  "POST" MODIFY ("POST_WRITER" NOT NULL ENABLE);

-- 자유게시판 댓글
CREATE TABLE  "REPLY" 
(	"REPLY_NO" NUMBER, 
"POST_NO" NUMBER, 
"REPLY_WRITER" VARCHAR2(20 BYTE), 
"REPLY_CONTENTS" VARCHAR2(500 BYTE), 
"REPLY_DATE" DATE DEFAULT SYSDATE
);
ALTER TABLE  "REPLY" ADD PRIMARY KEY ("REPLY_NO");
ALTER TABLE  "REPLY" MODIFY ("REPLY_CONTENTS" NOT NULL ENABLE);
ALTER TABLE  "REPLY" MODIFY ("REPLY_WRITER" NOT NULL ENABLE);
ALTER TABLE REPLY ADD CONSTRAINT FK_POST_NO FOREIGN KEY(POST_NO) REFERENCES POST(POST_NO) ON DELETE CASCADE;

-- 게시글 신고
CREATE TABLE "POST_REPORT" 
(	"P_REPORT_NO" NUMBER, 
"P_STATUS" VARCHAR2(2 BYTE) DEFAULT 'N', 
"POST_NO" NUMBER
);
ALTER TABLE "POST_REPORT" ADD PRIMARY KEY ("P_REPORT_NO");
ALTER TABLE POST_REPORT ADD CONSTRAINT POST_NO FOREIGN KEY(POST_NO) REFERENCES POST(POST_NO) ON DELETE CASCADE;

-- 댓글 신고
CREATE TABLE "REPLY_REPORT" 
(	"R_REPORT_NO" NUMBER, 
"REPLY_NO" NUMBER, 
"R_STATUS" VARCHAR2(2 BYTE) DEFAULT 'N', 
"POST_NO" NUMBER
);
ALTER TABLE "REPLY_REPORT" ADD PRIMARY KEY ("R_REPORT_NO");
ALTER TABLE REPLY_REPORT ADD CONSTRAINT FK_REPLY_NO FOREIGN KEY(REPLY_NO) REFERENCES REPLY(REPLY_NO) ON DELETE CASCADE;

-- 열람실
CREATE TABLE "READINGROOM" 
(	"R_RESERVATION_NO" NUMBER, 
"USER_ID" VARCHAR2(20 BYTE), 
"R_RESERVATION_DATE" DATE DEFAULT SYSDATE, 
"R_RESERVATION_TIME" VARCHAR2(20 BYTE), 
"SEAT_NO" VARCHAR2(20 BYTE)
);
ALTER TABLE "READINGROOM" ADD PRIMARY KEY ("R_RESERVATION_NO");

-- 스터디룸
CREATE TABLE "STUDYROOM" 
(	"S_RESERVATION_NO" NUMBER, 
"USER_ID" VARCHAR2(20 BYTE), 
"S_RESERVATION_DATE" VARCHAR2(20 BYTE), 
"S_RESERVATION_TIME" VARCHAR2(20 BYTE), 
"PURPOSE" VARCHAR2(500 BYTE), 
"PERSONNEL" VARCHAR2(20 BYTE)
);
ALTER TABLE "STUDYROOM" ADD PRIMARY KEY ("S_RESERVATION_NO");

-- 프로시저
--create or replace PROCEDURE DEL_KEYWORD
--IS
--BEGIN
--DELETE POPULAR_KEYWORD;
--END;

---- COMMENT
-- 회원
COMMENT ON TABLE USERS IS '회원';
COMMENT ON COLUMN "USERS"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "USERS"."USER_PWD" IS '비밀번호';
COMMENT ON COLUMN "USERS"."USER_NO" IS '회원번호';
COMMENT ON COLUMN "USERS"."USER_NAME" IS '이름';
COMMENT ON COLUMN "USERS"."USER_PHONE" IS '휴대폰번호';
COMMENT ON COLUMN "USERS"."USER_TYPE" IS '사용자구분';
COMMENT ON COLUMN "USERS"."USER_EMAIL" IS '이메일';
COMMENT ON COLUMN "USERS"."STUDENT_ID" IS '학번';
COMMENT ON COLUMN "USERS"."MAJOR" IS '전공';
COMMENT ON COLUMN "USERS"."PROFILE_PIC" IS '사진';
COMMENT ON COLUMN "USERS"."ANNUAL_FEE" IS '연회비';
COMMENT ON COLUMN "USERS"."PAY_DATE" IS '연회비납부일';
COMMENT ON COLUMN "USERS"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "USERS"."PASS_CHECK" IS '이용증발급여부';
COMMENT ON COLUMN "USERS"."APPROVAL_DATE" IS '승인일자';
COMMENT ON COLUMN "USERS"."END_DATE" IS '만료일자';
COMMENT ON COLUMN "USERS"."SOCIAL_ID" IS '소셜로그인계정';
COMMENT ON COLUMN "USERS"."SURVEY_CHECK" IS '취향설문여부';
COMMENT ON COLUMN "USERS"."LENDING_COPY" IS '대출가능권수';

-- 도서
COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "BOOK"."BOOK_NAME" IS '도서제목';
COMMENT ON COLUMN "BOOK"."BOOK_WRITER" IS '저자';
COMMENT ON COLUMN "BOOK"."BOOK_SUBJECT" IS '주제';
COMMENT ON COLUMN "BOOK"."PUBLISHER" IS '출판사';
COMMENT ON COLUMN "BOOK"."BOOK_YEAR" IS '발행연도';
COMMENT ON COLUMN "BOOK"."CALL_NO" IS '청구기호';
COMMENT ON COLUMN "BOOK"."ISBN" IS 'ISBN';
COMMENT ON COLUMN "BOOK"."BOOK_COVER" IS '표지';
COMMENT ON COLUMN "BOOK"."THEME" IS '테마';
COMMENT ON COLUMN "BOOK"."BOOK_STATE" IS '도서상태';
COMMENT ON COLUMN "BOOK"."UPDATE_DATE" IS '등록일자';
COMMENT ON COLUMN "BOOK"."LENDING_COUNT" IS '대출횟수';
COMMENT ON TABLE "BOOK"  IS '도서';

-- 대출
COMMENT ON COLUMN "BOOK_LENDING"."LENDING_NO" IS '대출번호';
COMMENT ON COLUMN "BOOK_LENDING"."LENDING_DATE" IS '대출일자';
COMMENT ON COLUMN "BOOK_LENDING"."RETURN_DATE" IS '반납일자';
COMMENT ON COLUMN "BOOK_LENDING"."EXTEND_COUNT" IS '연장횟수';
COMMENT ON COLUMN "BOOK_LENDING"."RECEIVE" IS '수령방법';
COMMENT ON COLUMN "BOOK_LENDING"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "BOOK_LENDING"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "BOOK_LENDING"."RETURN_STATE" IS '반납여부';
COMMENT ON TABLE "BOOK_LENDING"  IS '대출';

-- 택배
COMMENT ON COLUMN "PARCEL"."DELIVERY_NO" IS '택배번호';
COMMENT ON COLUMN "PARCEL"."LENDING_NO" IS '대출번호';
COMMENT ON COLUMN "PARCEL"."ADDR" IS '주소';
COMMENT ON COLUMN "PARCEL"."D_STATUS" IS '처리상태';
COMMENT ON TABLE "PARCEL"  IS '택배';

-- 관심도서
COMMENT ON COLUMN "INTERESTING_BOOK"."INTEREST_NO" IS '찜번호';
COMMENT ON COLUMN "INTERESTING_BOOK"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "INTERESTING_BOOK"."USER_ID" IS '회원아이디';
COMMENT ON TABLE "INTERESTING_BOOK"  IS '관심도서';

-- 예약
COMMENT ON COLUMN "BOOK_RESERVATION"."RSV_NO" IS '예약번호';
COMMENT ON COLUMN "BOOK_RESERVATION"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "BOOK_RESERVATION"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "BOOK_RESERVATION"."RSV_DATE" IS '예약날짜';
COMMENT ON COLUMN "BOOK_RESERVATION"."RSV_STATE" IS '예약알림상태';
COMMENT ON TABLE "BOOK_RESERVATION"  IS '예약';

-- 희망도서
COMMENT ON COLUMN "WISH_BOOK"."APPLY_NO" IS '신청번호';
COMMENT ON COLUMN "WISH_BOOK"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "WISH_BOOK"."BOOK_NAME" IS '도서명';
COMMENT ON COLUMN "WISH_BOOK"."BOOK_WRITER" IS '저자';
COMMENT ON COLUMN "WISH_BOOK"."PUBLISHER" IS '출판사';
COMMENT ON COLUMN "WISH_BOOK"."APPLY_STATUS" IS '처리상태';
COMMENT ON COLUMN "WISH_BOOK"."APPLY_DATE" IS '신청일';
COMMENT ON TABLE "WISH_BOOK"  IS '희망도서';

-- 서평
COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '서평번호';
COMMENT ON COLUMN "REVIEW"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "REVIEW"."REVIEW_STAR" IS '별점';
COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENTS" IS '내용';
COMMENT ON COLUMN "REVIEW"."REVIEW_DATE" IS '작성일';
COMMENT ON COLUMN "REVIEW"."REVIEW_STATUS" IS '작성여부';
COMMENT ON COLUMN "REVIEW"."USER_ID" IS '작성자';
COMMENT ON TABLE "REVIEW"  IS '서평';

-- 취향설문
COMMENT ON COLUMN "TASTE_SURVEY"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "TASTE_SURVEY"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "TASTE_SURVEY"."BOOK_NAME" IS '도서제목';
COMMENT ON COLUMN "TASTE_SURVEY"."BOOK_RATING" IS '별점';
COMMENT ON COLUMN "TASTE_SURVEY"."BOOK_SUBJECT" IS '주제';
COMMENT ON COLUMN "TASTE_SURVEY"."THEME" IS '테마';
COMMENT ON COLUMN "TASTE_SURVEY"."SURVEY_DATE" IS '설문일자';
COMMENT ON TABLE "TASTE_SURVEY"  IS '취향설문';

-- 취향
COMMENT ON COLUMN "TASTE"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "TASTE"."TASTE1" IS '취향1';
COMMENT ON COLUMN "TASTE"."TASTE2" IS '취향2';
COMMENT ON COLUMN "TASTE"."TASTE3" IS '취향3';
COMMENT ON TABLE "TASTE"  IS '취향';

-- 인기키워드
COMMENT ON COLUMN  "POPULAR_KEYWORD"."KEYWORD" IS '도서명';
COMMENT ON COLUMN  "POPULAR_KEYWORD"."SEARCH_DATE" IS '검색일';
COMMENT ON TABLE  "POPULAR_KEYWORD"  IS '인기키워드';

-- 공지사항
COMMENT ON TABLE "NOTICE" IS '공지사항';
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지번호';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_WRITER" IS '작성자';
COMMENT ON COLUMN "NOTICE"."N_CREATE_DATE" IS '작성일';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENTS" IS '내용';
COMMENT ON COLUMN "NOTICE"."VIEW_COUNT" IS '조회수';

-- 문의
COMMENT ON COLUMN  "QNA"."QNA_NO" IS '문의번호';
COMMENT ON COLUMN  "QNA"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN  "QNA"."REPLY_STATE" IS '답변상태';
COMMENT ON COLUMN  "QNA"."QNA_TITLE" IS '제목';
COMMENT ON COLUMN  "QNA"."QNA_CONTENT" IS '내용';
COMMENT ON COLUMN  "QNA"."QNA_WRITEDATE" IS '등록일';
COMMENT ON COLUMN  "QNA"."REPLY_CONTENT" IS '답변내용';
COMMENT ON COLUMN  "QNA"."REPLY_WRITEDATE" IS '답변작성일';
COMMENT ON COLUMN  "QNA"."REPLY_USERID" IS '답변작성자';
COMMENT ON TABLE  "QNA"  IS '문의';

-- 자유게시판
COMMENT ON COLUMN  "POST"."POST_NO" IS '글번호';
COMMENT ON COLUMN  "POST"."POST_WRITER" IS '작성자';
COMMENT ON COLUMN  "POST"."POST_TITLE" IS '제목';
COMMENT ON COLUMN  "POST"."POST_CONTENTS" IS '내용';
COMMENT ON COLUMN  "POST"."POST_DATE" IS '작성일';
COMMENT ON COLUMN  "POST"."P_VIEW_COUNT" IS '조회수';
COMMENT ON TABLE  "POST"  IS '자유게시판';

-- 자유게시판 댓글
COMMENT ON COLUMN  "REPLY"."REPLY_NO" IS '댓글번호';
COMMENT ON COLUMN  "REPLY"."POST_NO" IS '글번호';
COMMENT ON COLUMN  "REPLY"."REPLY_WRITER" IS '작성자';
COMMENT ON COLUMN  "REPLY"."REPLY_CONTENTS" IS '내용';
COMMENT ON COLUMN  "REPLY"."REPLY_DATE" IS '작성일';
COMMENT ON TABLE  "REPLY"  IS '댓글';

-- 게시글 신고
COMMENT ON COLUMN "POST_REPORT"."P_REPORT_NO" IS '신고번호';
COMMENT ON COLUMN "POST_REPORT"."P_STATUS" IS '처리상태';
COMMENT ON TABLE "POST_REPORT"  IS '게시글신고';

-- 댓글 신고
COMMENT ON COLUMN "REPLY_REPORT"."R_REPORT_NO" IS '글번호';
COMMENT ON COLUMN "REPLY_REPORT"."REPLY_NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY_REPORT"."R_STATUS" IS '처리상태';
COMMENT ON COLUMN "REPLY_REPORT"."POST_NO" IS '게시글번호';
COMMENT ON TABLE "REPLY_REPORT"  IS '댓글신고';

-- 열람실
COMMENT ON COLUMN "READINGROOM"."R_RESERVATION_NO" IS '예약번호';
COMMENT ON COLUMN "READINGROOM"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "READINGROOM"."R_RESERVATION_DATE" IS '예약일';
COMMENT ON COLUMN "READINGROOM"."R_RESERVATION_TIME" IS '예약시간';
COMMENT ON COLUMN "READINGROOM"."SEAT_NO" IS '좌석번호';
COMMENT ON TABLE "READINGROOM"  IS '열람실';

-- 스터디룸
COMMENT ON COLUMN "STUDYROOM"."S_RESERVATION_NO" IS '예약번호';
COMMENT ON COLUMN "STUDYROOM"."USER_ID" IS '회원아이디';
COMMENT ON COLUMN "STUDYROOM"."S_RESERVATION_DATE" IS '예약일';
COMMENT ON COLUMN "STUDYROOM"."S_RESERVATION_TIME" IS '예약시간';
COMMENT ON COLUMN "STUDYROOM"."PURPOSE" IS '사용목적';
COMMENT ON COLUMN "STUDYROOM"."PERSONNEL" IS '사용인원';
COMMENT ON TABLE "STUDYROOM"  IS '스터디룸';

---- INSERT DATA
-- 도서
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (1,'스피치 세계사 : 세상을 설득한 명연설 50편으로 현대사를 읽다','앤드루 버넷','총류','휴머니스트',2017,40,'9791160800821 03900','speech.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (2,'Java의 정석','남궁성','총류','도우출판',2016,5,'9788994492032','java.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (3,'생활코딩! 파이썬','이고잉, 장용하','총류','범',2020,5,'9791196058470 13000','python.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (4,'먼길로 돌아갈까?','게일 콜드웰','총류','문학동네',2021,70,'9788954681834 03840','longpath.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (5,'어른의 세렌디피티','심세은','총류','마음세상',2020,41,'9791156363903','serendipity.jpg','관계','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (6,'스프링 MVC 하루만에 배우기','연서은','총류','부크크',2020,5,'9791137227392 03000','mvc.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (7,'혼자 공부하는 자바스크립트 : 1:1 과외하듯 배우는 프로그래밍 자습서','윤인성','총류','한빛미디어',2021,5,'9791162243671 94000','selfjs.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (8,'Node.js 마이크로서비스 코딩 공작소','정대천','총류','길벗',2018,5,'9791160504217 93000','nodejs.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (9,'이것이 오라클이다 : Oracle 설치부터 PL / SQL 정복까지!','우재남','총류','한빛미디어',2018,5,'9791162240489 93000','oracle.jpg','자기계발','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (10,'저는 인문학이 처음인데요 : 교양인이 되기 위한 내 생애 첫 인문학','박홍순','총류','한빛비즈',2021,1,'9791157844999','first-humanities.jpg','자기계발','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (11,'어제와 똑같은 내가 싫어서 나를 바꾸기 시작했습니다','전도훈','철학','굿위즈덤',2021,199,'9791191447460 03190','yesterday.jpg','습관','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (12,'좋은 관계는 듣기에서 시작된다 : 듣기의 기술이 바꾸는 모든 것에 대하여','케이트 머피','철학','21세기북스',2021,189,'9788950989767 03320','good-relation.jpg','관계','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (13,'혼자 있어도 외롭지 않게 : 내성적이고 예민한 사람들을 위한 심리 수업','정교영','철학','샘터',2021,182,'9788946473850 03180','alone.jpg','습관','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (14,'철학으로 읽는 괴테 니체 바그너','승계호','철학','반니',2014,165,'9791185435176','gnb.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (15,'우울한 날엔 니체','발타자르 토마스','철학','자음과모음',2018,165,'9791163422310','gloomy.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (16,'그저 양심이 없을 뿐입니다','마사스타우트','철학','사계절',2021,184,'9791160947359 03180','conscience.jpg','관계','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (17,'당신이 숨기고 있는 것들 : 인생의 판을 바꾸는 무의식의 힘','정도언','철학','지와인',2021,181,'9791191521009 03180','unconscious.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (18,'씽크 어게인 : 논쟁의 기술','월터 시넛 암스트롱','철학','해냄',2020,179,'9788965749882 03170','think-again.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (19,'돼지를 키운 채식주의자','이동호','철학','창비',2021,194,'9788936486778 03300','vegetarian.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (20,'소크라테스 익스프레스 : 철학이 우리 인생에 스며드는 순간','에릭 와이너','철학','어크로스',2021,102,'9791190030922 03100','socrates.jpg','자기계발','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (21,'무소유','법정','종교','범우사',2004,220,'8908041311','mosou.jpg','힐링','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (22,'달마어록','김태완','종교','불광출판사',2012,228,'9788989590316','dalma.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (23,'처음 만난 관무량수경','김호성','종교','동국대학교 출판부',2019,223,'9788978019514 03220','newjoin.jpg','자기계발','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (24,'아인슈타인의 우주적 종교와 불교','김성구','종교','불광출판사',2018,225,'9788974793937 03220','bulscience.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (25,'스님의 남자친구','일광스님','종교','불교신문사',2018,220,'9791189147037 03810','bulmanf.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (26,'백담사 무문관 일기','정휴','종교','우리출판사',2017,224,'9788975613357 03220','backdam.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (27,'성철 편전','김택근','종교','모과나무',2017,220,'9791187280101 03220','sungchul.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (28,'문수진실명경 역해','중암','종교','운주사',2017,229,'9788957464984 93220','munjin.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (29,'영산재','법현','종교','운주사',2019,227,'9788957465448 03670','yongsan.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (30,'선의 통쾌한 농담','김영욱','종교','김영사',2020,228,'9788934995050 03650','sunjoke.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (31,'어른의 어휘력','유선경','언어','앤의서재',2020,802,'9791190710053 03800','adult.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (32,'언어의 탄생 : 영어의 역사, 그리고 세상 모든 언어에 관하여','빌 브라이슨','언어','다산북스',2021,740,'9791130638324 03700','birth.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (33,'동사의 맛 교정의 숙수가 알뜰살뜰 차려 낸 우리말 움직씨 밥상','김정선','언어','유유',2015,815,'9791185152196 03710','taste.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (34,'더 문법하고 싶은 문법 : 국어 교사와 예비 교사를 위한 국어 문법 즉문즉답','신승용,안윤주','언어','역락',2021,715,'9791162445648 93710','more.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (35,'언 다르고 어 다르다 : 슬기로운 낱말 공부','김철호','언어','돌베개',2020,714,'9788971992012 03710','unelseun.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (36,'나는 생각하고 말하는 사람이 되기로 했다 : 말에 품격을 더하는 언어 감수성 수업','홍승우','언어','웨일북',2021,710,'9791190313933 03800','ithink.jpg','관계','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (37,'내 언어에 속지 않는 법 : 한국어에 상처받은 이들을 위한 영어 수업','허새로미','언어','현암사',2019,740,'9788932320052 03700','nolie.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (38,'글자 풍경 : 글자에 아로새긴 스물일곱 가지 세상','유지원','언어','을유문화사',2019,818,'9788932473956 03600','charview.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (39,'플루언트 = Fluent : 영어 유창성의 비밀','조승연','언어','미래엔',2016,740,'9788937846243 03300','fluent.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (40,'언어의 뇌과학','알베르트 코스타','언어','현대지성',2020,707,'788955619447 03300','brain.jpg','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (41,'영재를 만드는 기적의 뇌 공부법','김동하','사회과학','지구별출판사',2015,373,'9791190950312 03220','영재를 만드는 기적의 뇌.PNG','습관','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (42,'프레시니스 코드 : 지금 글로벌 패션하우스들은 어떻게 유혹하는가','조엘 킴벡','사회과학','리더스북:웅진씽크빅',2021,325,'9788901252506 03320','프레니시스 코드.PNG','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (43,'(사회복지연구를 위한) SPSS 기초통계','허만세','사회과학','양서원',2021,338,'9788999411540 93330','사회복지연구를 위한 기초통계.PNG','경제','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (44,'2021 재개발 주택세금 길라잡이 : 2022년 세법개정안 반영','김영인','사회과학','더존테크윌',2021,329,'9791163060505 13320','2021 재개발 주택세금.PNG','경제','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (45,'유튜브 주식채널의 정보효과와 위험요인','남길남','사회과학','자본시장연구원',2021,327,'9788960892729 93320','유튜브 주식채널.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (46,'크게 생각하는 사람이 크게 이룬다','박가람','사회과학','굿웰스북스',2021,325,'9791191447187 03190','크게 생각하는 사람이.PNG','관계','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (47,'관광 스토리텔링','김주연','사회과학','백산출판사',2021,326,'9791165673871 13980','관광 스토리텔링.PNG','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (48,'국제경영의 이론과 실제','박종돈','사회과학','청람',2021,325,'9788959728381 93320','국제경영의 이론과 실제.PNG','경제','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (49,'직장인을 위한 부동산 가치투자','이병훈','사회과학','바른북스',2021,379,'9791157211616 93330','직장을위한 부동산.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (50,'테크네 상상력 : 인간-기계-문화를 관통하며','김진택','사회과학','바른북스',2021,331,'9791165454883 03500','테크네 상상력.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (51,'우리의 태도가 과학적일 때','이종필','자연과학','사계절',2021,404,'9791160947342 03400','우리의 태도가 과학적일 때.PNG','관계','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (52,'(세상을 바꾼) 화학','원정현','자연과학','리베르스쿨',2018,430,'9788965822912 04400','세상을 바꾼 화학.PNG','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (53,'(세상을 바꾼) 지구과학','원정현','자연과학','리베르스쿨',2018,440,'9788965822929 04400','세상을 바꾼 지구과학.PNG','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (54,'정수 귀신 : 수학 소녀의 비밀노트','유키 히로시','자연과학','영림카디널:와이엘씨',2021,410,'9788984012424 04410','정수귀신.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (55,'식물학자의 노트 식물이 내게 들려준 이야기 : 큰글자책','신혜우','자연과학','김영사',2021,480,'9788934904885 04400','식물학자의 노트.PNG','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (56,'식물에서 길을 찾다','최문형','자연과학','Nexen Media',2020,480,'9791190583350 03520','식물에서 길을 찾다.PNG','힐링','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (57,'NCS 수리능력 만점을 위한 빠른 계산 : 워크북+무료NCS특강','김현철','자연과학','시대고시기획',2021,410,'9791138304429 13320','수리능력 만점을 위한 빠른 계산.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (58,'보따니스트 : 모험하는 식물학자들','마르 장송','자연과학','가지',2021,480,'9791186440711 03400','보따니스트.PNG','힐링','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (59,'(수학은 어렵지만) 확률·통계는 알고 싶어','요비노리 다쿠미','자연과학','한스미디어:한즈미디어',2021,413,'9791160077179 03410','확률 통계는 알고싶어.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (60,'(환경직 공무원) 화학 : 7·9급 공무원 시험 대비','신동성,임후연 공저','자연과학','세진사',2021,430,'9791160454819 13530','환경직 공무원.PNG','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (61,'기적을 만드는 걷기 혁명 : 가장 안전하고 쉬운 100세 건강 프로젝트','이수경','기술과학','굿웰스북스',2021,517,'9791191447361 03510','기적을 만드는 걷기 혁명.png','건강','대출가능',to_date('21/11/03','RR/MM/DD'),5);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (62,'병원구매관리','남상요, 윤기섭 공저','기술과학','계축문화사',2021,517,'9788956296531 93510','hospital.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (63,'산부인과학 : 지침과 개요','대한산부인과학회','기술과학','군자출판사',2021,516,'9791159557606 93510','산부인과학.png','건강','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (64,'정보통신관계법규 해설','송현섭, 이곡부 공저','기술과학','청문각',1992,560,'8970880208 93560','정보통신관계법규해설.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (65,'기흐르는 신체','이시다 히데미 지음, 이동철 옮김','기술과학','열린책들',1996,512,'8932901376 93510','기흐르는 신체.png','건강','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (66,'신호와 시스템','최태영, 나상신 공저','기술과학','대영사',1996,569,'897163023X 93560','신호와 시스템.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (67,'아트 메이크업','김양은, 이미희, 송미영, 김은주 공저','기술과학','광문각',2009,593,'9788970935027 93590','아트메이크업.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (68,'홍차, 느리게 매혹되다','최예선','기술과학','모요사',2009,594,'9788996253709 03810','홍차 느리게 매혹되다.png','힐링','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (69,'자동차 구조와 원리 : 이지','이재곤','기술과학','홍릉과학출판사',2016,556,'9791156004523 93550','자동차 구조와 원리.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (70,'관광서비스 지원관리 : 국제의료관광 코디네이터','나승권','기술과학','상학당',2017,517,'9788965870944 93510','관광서비스 지원관리.png','기술','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (71,'지중해 문명과 단군조선','박용숙','역사','집문당',1996,911,'8930304079 93910','지중해 문명과 단군조선.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (72,'한국인의 생활과 풍속 상','임종국','역사','아세아문화사',1995,911,'8942812538 94900','한국인의 생활과 풍속.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (73,'우주가 바뀌던 날 그들은 무엇을 했나','제임스 버크 지음, 장석봉 옮김','역사','지호',2000,909,'8986270382 03900','우주가 바뀌던 날 그들은 무엇을 했나.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (74,'민란의 시대 : 조선시대의 민란과 변란들','고성훈 외 지음','역사','가람기획',2000,911,'8984350281 03910','민란의 시대.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (75,'모터사이클 다이어리 : 라틴 아메리카 여행기','체 게바라','역사','황매',2005,985,'8990462711 03800','모터사이클 다이어리.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (76,'서양사의 이해','임희완','역사','박영사',2003,920,'8910950102 93920','서양사의 이해.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (77,'흉노 : 지금은 사라진 고대 유목국가 이야기','사와다 이사오 지음, 김숙경 옮김','역사','아이필드',2007,912,'8989938767 03900','흉노.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),11);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (78,'세계를 속인 거짓말. 문명과 전쟁편','이종호','역사','뜨인돌',2010,909,'9788958072744 03900','세계를 속인 거짓말.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (79,'그리스 사상과 아랍 문명 : 번역 운동과 이슬람의 지적혁신','디미트리 구타스 지음, 정영목 옮김','역사','글항아리',2013,909,'9788967350376 93900','그리스 사상과 아랍문명.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),6);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (80,'(여행자를 위한)나의 문화유산 답사기 1','유홍준','역사','창비',2021,981,'9788936472917','여행자를 위한 나의 문화유산답사기1.png','여행','대출가능',to_date('21/11/03','RR/MM/DD'),8);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (81,'한무제 : 중국 역사의 새로운 장을 열다','요시카와 고지로 지음, 장원철 옮김','역사','AK(에이케이 커뮤니케이션즈)',2021,912,'9791127443822 04910','한무제.png','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),5);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (82,'봄날의 고양이처럼','윤제','문학','BookPOD(북팟)',2021,818,'9791166632136','springcat.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),6);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (83,'장엄호텔 : 마리 르도네 소설','마리 르도네','문학','열림원',2021,863,'9791170400462','majestic.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (84,'어른을 위한 수면 동화 : 당신의 불면증을 잠재워줄 열 편의 이야기','이타르 아델','문학','가나문화콘텐츠',2021,853,'9791168090002','foradult.jpg','힐링','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (85,'잠꼬대','이성민','문학','바른북스',2021,811,'9791165454944','sleeptalking.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (86,'세월이 그린 그림','오정근','문학','바른북스사',2021,811,'9791165454784','time.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),4);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (87,'은유의 사회학 = Metaphorical sociology','류재엽','문학','PRSG(푸른생각)',2021,810,'9788991918993','sociology.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (88,'(좌충우돌) 그리스 인턴 생존기','김수정','문학','바른북스',2021,818,'9791165454746','greece.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (89,'행복은 주름살이 없다 : 안가엘 위옹 장편소설','안가엘','문학','청미',2021,863,'9791189134273','wrinkles.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (90,'동물농장','조지 오웰','문학','팡세미니',2021,843,'9788961559362','animalfarm.jpg','인사이트','대출가능',to_date('21/11/03','RR/MM/DD'),6);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (91,'치카를 찾아서','미치 앨봄','문학','살림',2021,844,'9788952243096','chica.jpg','자기계발','대출가능',to_date('21/11/03','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (92,'자연스러운 몸짓 : 일러스트 포즈집 : 캐릭터의 자연스러운 동작 표현법','하비재팬','예술','AK Hobby Book',2021,657,'9791127446918','naturalgestures.jpg','감성','대출가능',to_date('21/11/03','RR/MM/DD'),0);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (161,'음식 문화와 영화인문학 : 영화로 읽는 음식 문화와 영화 서사의 동력으로서 음식 문화','김남석','예술','연극과인간',2021,688,'9788957867853','filmhumanities.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (162,'세계사 속의 서양 연극사 = The history of theatre with world history : 연극, 어디까지 궁금하니?','전형재','예술','푸른사상',2021,684,'9791130818153','theaterhistory.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),2);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (163,'킹 클로프 : 리버풀 왕조를 재건한 클로프의 전술 콘셉트','리 스콧','예술','삼호미디어',2021,695,'9788978496452','kingklopp.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),3);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (164,'문화유산을 읽는 새로운 시각, 빅데이터 : 고고미술사학과 대학원생들의 빅데이터 체험기','김민서','예술','Bookpod(북팟)',2021,609,'9791166632365','bigdata.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),1);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (165,'라르스 툰비에르크','페르 린스트룀','예술','열화당',2021,668,'9788930107105','larstunbierk.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),4);
Insert into BOOK (BOOK_NO,BOOK_NAME,BOOK_WRITER,BOOK_SUBJECT,PUBLISHER,BOOK_YEAR,CALL_NO,ISBN,BOOK_COVER,THEME,BOOK_STATE,UPDATE_DATE,LENDING_COUNT) values (167,'어떤 그림 : 존 버거와 이브 버거의 편지','존 버거','예술','열화당',2021,650,'9788930106993','whatpicture.jpg','인사이트','대출가능',to_date('21/11/12','RR/MM/DD'),2);

--공지사항
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올대학교 규장각 홈페이지입니다~','daolLibrary',SYSDATE,'다올대학교 규장각 홈페이지입니다~','130');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올 규장각 홈페이지를 방문해주셔서 감사합니다.','daolLibrary',SYSDATE,'다올 규장각 홈페이지에 방문해주신 여러분 환영합니다. 궁금한점이나 불편하신 사항이 있으시면 문의 주세요.','14');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'궁금하신 사항은 문의를 통해 물어봐주세요!','daolLibrary',SYSDATE,'궁금하신 사항은 문의를 통해 물어봐주세요!','59');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'도서관 시설 이용안내','daolLibrary',SYSDATE,'도서관 시설 이용안내는 홈페이지 좌측 도서관 소개를 통해 확인해주세요.','23');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'인기 도서','daolLibrary',SYSDATE,'인기 도서는 자료검색 >> 대출베스트에서 확인가능합니다.','13');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'취향분석 설문 시스템 오픈','daolLibrary',SYSDATE,'마이페이지에서 설문 가능합니다 !','5');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'열람실, 스터디룸 이용안내','daolLibrary',SYSDATE,'홈페이지 좌측 도서관 소개를 통해 확인가능합니다!','6');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다독자 순위','daolLibrary',SYSDATE,'메인 홈페이지에서 확인가능합니다~ 많은 이용 바랍니다.','8');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올대학교 규장각 홈페이지 공지사항','daolLibrary',SYSDATE,'다올대학교 규장각 홈페이지 공지사항','11');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'게시글 신고 안내','daolLibrary',SYSDATE,'게시글 신고 안내입니다.','10');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올대학교 학생 필독','daolLibrary',SYSDATE,'다올대학교 학생 필독!!','120');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올대학교 규장각 홈페이지입니다~','daolLibrary',SYSDATE,'다올대학교 규장각 홈페이지입니다~','13');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올 규장각 홈페이지를 방문해주셔서 감사합니다.','daolLibrary',SYSDATE,'다올 규장각 홈페이지에 방문해주신 여러분 환영합니다. 궁금한점이나 불편하신 사항이 있으시면 문의 주세요.','59');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'궁금하신 사항은 문의를 통해 물어봐주세요!','daolLibrary',SYSDATE,'궁금하신 사항은 문의를 통해 물어봐주세요!','23');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'도서관 시설 이용안내','daolLibrary',SYSDATE,'도서관 시설 이용안내는 홈페이지 좌측 도서관 소개를 통해 확인해주세요.','54');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'인기 도서','daolLibrary',SYSDATE,'인기 도서는 자료검색 >> 대출베스트에서 확인가능합니다.','13');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'취향분석 설문 시스템 오픈','daolLibrary',SYSDATE,'마이페이지에서 설문 가능합니다 !','11');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'열람실, 스터디룸 이용안내','daolLibrary',SYSDATE,'홈페이지 좌측 도서관 소개를 통해 확인가능합니다!','10');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다독자 순위','daolLibrary',SYSDATE,'메인 홈페이지에서 확인가능합니다~ 많은 이용 바랍니다.','20');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'다올대학교 규장각 홈페이지 공지사항','daolLibrary',SYSDATE,'다올대학교 규장각 홈페이지 공지사항','23');
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'게시글 신고 안내','daolLibrary',SYSDATE,'게시글 신고 안내입니다.','11');

--회원
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('daolLibrary','1234',0,'관리자','01012345678','관리자','daolLibrary1@gmail.com',null,null,null,null,to_date('21/11/09','RR/MM/DD'),to_date('21/11/09','RR/MM/DD'),'N',to_date('21/11/09','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'),null,'N',3);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user01','user01',1,'김루이','01000000001','일반','daollibrary@gmail.com',0,null,'profile.jfif','납부',to_date('21/11/12','RR/MM/DD'),to_date('21/11/09','RR/MM/DD'),'Y',to_date('21/11/10','RR/MM/DD'),to_date('22/11/10','RR/MM/DD'),null,'Y',1);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user02','user02',2,'김로미','01000000002','일반','tjrdls000@naver.com',0,null,null,'납부',to_date('21/11/15','RR/MM/DD'),to_date('21/11/09','RR/MM/DD'),'Y',null,null,null,'Y',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user03','user03',3,'김다정','01000000003','일반','daollibrary@gmail.com',0,null,null,'납부',to_date('21/11/19','RR/MM/DD'),to_date('21/11/09','RR/MM/DD'),'Y',to_date('21/11/19','RR/MM/DD'),to_date('22/11/19','RR/MM/DD'),null,'Y',2);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('khuser01','1234',4,'윤석인','01011111111','일반','tjrdls000@naver.com',null,null,'profile.jfif',null,to_date('21/11/04','RR/MM/DD'),to_date('21/11/04','RR/MM/DD'),'N',to_date('21/11/04','RR/MM/DD'),to_date('21/11/22','RR/MM/DD'),null,'Y',6);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('jang123','1234',5,'장재웅','01001010101','일반','hana02031@naver.com',0,null,null,null,null,to_date('21/11/16','RR/MM/DD'),'N',null,null,'1993554315K','Y',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('song1007','song1007',6,'송윤수','01012341234','일반','suyunsong1007@gmail.com',0,null,null,'납부',null,to_date('21/11/20','RR/MM/DD'),'Y',null,to_date('22/11/22','RR/MM/DD'),null,'N',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('songStudent','songStudent',7,'송윤수','01032113211','학생','song@daol.ar.kr',20191003,'인문사회',null,'납부',to_date('21/11/22','RR/MM/DD'),to_date('21/11/20','RR/MM/DD'),'N',null,null,null,'Y',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('tjrdls000','1234',8,'윤석인','01086046961','학생','daol@daol.co.kr',20150566,'예체능','로그인1.PNG',null,null,to_date('21/11/05','RR/MM/DD'),'N',null,null,null,'Y',0);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('tjrdls123','obxfqboeeomd',9,'윤석인','01086046961','일반','seokin6961@gmail.com',0,null,null,null,null,to_date('21/11/06','RR/MM/DD'),'N',null,null,null,'N',0);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('1234','1234',10,'이지훈','1111','학생','daol@daol.co.kr',1234,'인문사회','한국인의 생활과 풍속.png',null,null,to_date('21/11/07','RR/MM/DD'),'N',null,null,null,'Y',0);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user04','user04',11,'김서연','01045325878','학생','user04@daol.co.kr',15240477,'의학',null,null,null,to_date('21/11/16','RR/MM/DD'),'N',null,null,null,'N',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user05','user05',12,'박민서','01045226877','학생','user05@daol.co.kr',18240576,'자연과학',null,null,null,to_date('21/11/16','RR/MM/DD'),'N',null,null,null,'N',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('user06','user06',13,'서지우','01045589455','학생','user06@daol.co.kr',21152477,'공학',null,null,null,to_date('21/11/16','RR/MM/DD'),'N',null,null,null,'Y',5);
Insert into USERS (USER_ID,USER_PWD,USER_NO,USER_NAME,USER_PHONE,USER_TYPE,USER_EMAIL,STUDENT_ID,MAJOR,PROFILE_PIC,ANNUAL_FEE,PAY_DATE,ENROLL_DATE,PASS_CHECK,APPROVAL_DATE,END_DATE,SOCIAL_ID,SURVEY_CHECK,LENDING_COPY) values ('thdus1','thdus1',14,'강소연','01011112222','일반','soyeonash@gmail.com',0,null,null,'납부',to_date('21/11/19','RR/MM/DD'),to_date('21/11/09','RR/MM/DD'),'Y',null,to_date('22/11/19','RR/MM/DD'),null,'Y',0);

COMMIT;